version: "3.8"
services:
  mongodb:
    image: bitnami/mongodb:7.0.8
    # image: bitnami/mongodb:4.4.13    # Use this version for Apple M1 Chip
    restart: always
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=mongo
      - MONGODB_REPLICA_SET_NAME=laf
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${SYS_DB}
      - MONGODB_USERNAME=${SYS_DB_USER}
      - MONGODB_PASSWORD=${SYS_DB_PASSWORD}
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - "27017:27017"
    networks:
      - laf_shared_network
networks:
  laf_shared_network:
    external: true

volumes:
  db-data:
